service: serverless-cifar
 
provider:
  name: aws #cloud provider
  region: ap-south-1 #region (mumbai)
  memorySize: 3008 #memory usage
  timeout: 300 
 
functions:
  cifar:
    image: 258326714772.dkr.ecr.ap-south-1.amazonaws.com/cifar10_serverless:latest 
    events:
      - http:
          path: inference 
          method: post 
          cors: true