# @package _global_

defaults:
  - _self_
  - paths: default.yaml
  - hydra: default.yaml

task_name: "demo_scripted"

# checkpoint is necessary for demo
ckpt_path: "/workspace/emlo2-session2/logs/train/runs/2022-10-20_07-40-44/model.script.pt"