_target_: src.models.cifar10_module.CIFAR10LitModule

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.001
  weight_decay: 5e-4

net:
  _target_: timm.create_model
  model_name: 'resnet18'
  num_classes: 10
  pretrained: true
